### ISSUE TITLE
Long error message pushes down the next line

### ISSUE THREAD

**Issue by nowaylifer** [rachartier/tiny-inline-diagnostic.nvim#65]
It only happens with huge error messages like in vtsls lsp.

https://github.com/user-attachments/assets/4eb272d5-1d74-484b-a273-3f0805fb4d8b

**Comment by uwla** [comment]
This error also happens too me, but only if the the number of lines in the file is less than the terminal height. For example, if there are 10 lines in a typescript file, the inline error preview pushes the next line to the bottom. If I added code in this file such that it has, let us say, 100 lines, then the same inline error does not push the line to the bottom

**Comment by rachartier** [comment]
See https://github.com/rachartier/tiny-inline-diagnostic.nvim/issues/53#issuecomment-2435255822

I do not know what the ideal solution looks like yet, but I will take a look.

**Comment by rachartier** [comment]
Hi again,

It should be fixed now !

**Comment by nowaylifer** [comment]
yes, but error signs are still shown in the gutter along the height of an error message

![image](https://github.com/user-attachments/assets/f28f3028-d365-4738-93c0-1281ca109139)

**Comment by rachartier** [comment]
Do you use a plugin with your status column ?

**Comment by nowaylifer** [comment]
> Do you use a plugin with your status column ?

yes, folke/snacks.nvim

**Comment by rachartier** [comment]
I will open an issue on snack.nvim. I'll come back to you when I have more info

**Comment by rachartier** [comment]
Seems fixed now @nowaylifer: https://github.com/folke/snacks.nvim/issues/198

Thanks Folke!

**Comment by nowaylifer** [comment]
Good job, thanks!
